// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFhq5mUsFDsac2TDlxhKC_ZvgL2cAEyfE',
    appId: '1:566036891809:web:315270e6ecdf4e282dc8e0',
    messagingSenderId: '566036891809',
    projectId: 'underground-apparel-project',
    authDomain: 'underground-apparel-project.firebaseapp.com',
    storageBucket: 'underground-apparel-project.firebasestorage.app',
    measurementId: 'G-69P59WE3LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRtbDhsl4fwgHJcdJLlBMaLpIVEB_YcdU',
    appId: '1:566036891809:android:1a586dcce6cf93662dc8e0',
    messagingSenderId: '566036891809',
    projectId: 'underground-apparel-project',
    storageBucket: 'underground-apparel-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-CcQWA4K8s_D-gNrgv0M1qsY0XvRBblU',
    appId: '1:566036891809:ios:eab24bbbd733ff6a2dc8e0',
    messagingSenderId: '566036891809',
    projectId: 'underground-apparel-project',
    storageBucket: 'underground-apparel-project.firebasestorage.app',
    iosBundleId: 'com.example.ua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-CcQWA4K8s_D-gNrgv0M1qsY0XvRBblU',
    appId: '1:566036891809:ios:eab24bbbd733ff6a2dc8e0',
    messagingSenderId: '566036891809',
    projectId: 'underground-apparel-project',
    storageBucket: 'underground-apparel-project.firebasestorage.app',
    iosBundleId: 'com.example.ua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFhq5mUsFDsac2TDlxhKC_ZvgL2cAEyfE',
    appId: '1:566036891809:web:d7be177fb674b64a2dc8e0',
    messagingSenderId: '566036891809',
    projectId: 'underground-apparel-project',
    authDomain: 'underground-apparel-project.firebaseapp.com',
    storageBucket: 'underground-apparel-project.firebasestorage.app',
    measurementId: 'G-Z5S41JKT0C',
  );
}
